version: '3.8'

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mypass
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  timescale_data:
